version: '3.1'

services:
  db:
    hostname: db
    image: postgres:13.5
    restart: always
    volumes:
      - pgdata:/pgdata
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
      - PGDATA=pgdata
    ports:
      - "127.0.0.1:${PG_PORT}:5432"

  app:
    hostname: app
    build:
      context: .
      args:
        - APP_CONFIG=${APP_CONFIG}
    env_file:
      - .env
    volumes:
      - ./upload:/app/upload
    ports:
      - "127.0.0.1:${APP_PORT}:8080"
    depends_on:
      - db

volumes:
  pgdata:

