// Code generated by MockGen. DO NOT EDIT.
// Source: user.go

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	reflect "reflect"

	entities "awcoding.com/back/pkg/domain/entities"
	gomock "github.com/golang/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetByEmailPassword mocks base method.
func (m *MockUserRepository) GetByEmailPassword(email, password string) (*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmailPassword", email, password)
	ret0, _ := ret[0].(*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmailPassword indicates an expected call of GetByEmailPassword.
func (mr *MockUserRepositoryMockRecorder) GetByEmailPassword(email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmailPassword", reflect.TypeOf((*MockUserRepository)(nil).GetByEmailPassword), email, password)
}

// GetById mocks base method.
func (m *MockUserRepository) GetById(id int) (*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockUserRepositoryMockRecorder) GetById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockUserRepository)(nil).GetById), id)
}

// MockUserCases is a mock of UserCases interface.
type MockUserCases struct {
	ctrl     *gomock.Controller
	recorder *MockUserCasesMockRecorder
}

// MockUserCasesMockRecorder is the mock recorder for MockUserCases.
type MockUserCasesMockRecorder struct {
	mock *MockUserCases
}

// NewMockUserCases creates a new mock instance.
func NewMockUserCases(ctrl *gomock.Controller) *MockUserCases {
	mock := &MockUserCases{ctrl: ctrl}
	mock.recorder = &MockUserCasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCases) EXPECT() *MockUserCasesMockRecorder {
	return m.recorder
}

// GetByEmailPassword mocks base method.
func (m *MockUserCases) GetByEmailPassword(email, password string) (*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmailPassword", email, password)
	ret0, _ := ret[0].(*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmailPassword indicates an expected call of GetByEmailPassword.
func (mr *MockUserCasesMockRecorder) GetByEmailPassword(email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmailPassword", reflect.TypeOf((*MockUserCases)(nil).GetByEmailPassword), email, password)
}

// GetById mocks base method.
func (m *MockUserCases) GetById(id int) (*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockUserCasesMockRecorder) GetById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockUserCases)(nil).GetById), id)
}
