basePath: /
definitions:
  auth_controller.SignInInput:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  entities.Auth:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/entities.User'
    type: object
  entities.Upload:
    properties:
      id:
        type: integer
      name:
        type: string
      path:
        type: string
      type:
        type: string
    type: object
  entities.User:
    properties:
      avatar:
        $ref: '#/definitions/entities.Upload'
      avatarId:
        type: integer
      email:
        type: string
      id:
        type: integer
    type: object
  response.errorResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample REST API server.
  title: Swagger Back API
  version: "1.0"
paths:
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: Вход по логину и паролю
      parameters:
      - description: SignIn information
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth_controller.SignInInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Auth'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.errorResponse'
      summary: Вход
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
